# This is the workflow for the CI/CD and release
#
name: Release

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha

jobs:
  cancel-runs:
    name: '▶️ actions'
    uses: ATOS-Actions/actions/.github/workflows/cancel-workflow.yml@v1

  lint-code:
    name: '▶️ actions'
    needs: [cancel-runs]
    uses: ATOS-Actions/actions/.github/workflows/lint-code.yml@v1

  test:
    name: '📌'
    needs: [lint-code]
    uses: ./.github/workflows/test.yml

  release:
    name: '▶️ actions'
    needs: [lint-code, test]
    uses: ATOS-Actions/actions/.github/workflows/release.yml@v1
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
